/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_int = 1,
  anon_sym_void = 2,
  anon_sym_float = 3,
  anon_sym_double = 4,
  anon_sym_char = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_EQ = 10,
  anon_sym_SEMI = 11,
  anon_sym_return = 12,
  sym_identifier = 13,
  sym_number = 14,
  sym_source_file = 15,
  sym__statement = 16,
  sym_function_definition = 17,
  sym_type = 18,
  sym_parameter_list = 19,
  sym_compound_statement = 20,
  sym_assignment_statement = 21,
  sym_return_statement = 22,
  sym_expression_statement = 23,
  sym_variable_declaration = 24,
  sym_expression = 25,
  aux_sym_source_file_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_int] = "int",
  [anon_sym_void] = "void",
  [anon_sym_float] = "float",
  [anon_sym_double] = "double",
  [anon_sym_char] = "char",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_return] = "return",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_function_definition] = "function_definition",
  [sym_type] = "type",
  [sym_parameter_list] = "parameter_list",
  [sym_compound_statement] = "compound_statement",
  [sym_assignment_statement] = "assignment_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_return] = anon_sym_return,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_function_definition] = sym_function_definition,
  [sym_type] = sym_type,
  [sym_parameter_list] = sym_parameter_list,
  [sym_compound_statement] = sym_compound_statement,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 3,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 10,
  [18] = 12,
  [19] = 13,
  [20] = 11,
  [21] = 9,
  [22] = 14,
  [23] = 15,
  [24] = 16,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 27,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 36,
  [40] = 40,
  [41] = 37,
  [42] = 42,
  [43] = 35,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '(', 8,
        ')', 9,
        ';', 13,
        '=', 12,
        'c', 21,
        'd', 27,
        'f', 24,
        'i', 25,
        'r', 20,
        'v', 28,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == ';') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_void);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_double);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_char);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__statement] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_type] = STATE(47),
    [sym_assignment_statement] = STATE(2),
    [sym_return_statement] = STATE(2),
    [sym_expression_statement] = STATE(2),
    [sym_variable_declaration] = STATE(2),
    [sym_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_type] = STATE(47),
    [sym_assignment_statement] = STATE(4),
    [sym_return_statement] = STATE(4),
    [sym_expression_statement] = STATE(4),
    [sym_variable_declaration] = STATE(4),
    [sym_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_return] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(5),
    [sym_function_definition] = STATE(5),
    [sym_type] = STATE(45),
    [sym_assignment_statement] = STATE(5),
    [sym_return_statement] = STATE(5),
    [sym_expression_statement] = STATE(5),
    [sym_variable_declaration] = STATE(5),
    [sym_expression] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_number] = ACTIONS(11),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(4),
    [sym_function_definition] = STATE(4),
    [sym_type] = STATE(47),
    [sym_assignment_statement] = STATE(4),
    [sym_return_statement] = STATE(4),
    [sym_expression_statement] = STATE(4),
    [sym_variable_declaration] = STATE(4),
    [sym_expression] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_int] = ACTIONS(23),
    [anon_sym_void] = ACTIONS(23),
    [anon_sym_float] = ACTIONS(23),
    [anon_sym_double] = ACTIONS(23),
    [anon_sym_char] = ACTIONS(23),
    [anon_sym_return] = ACTIONS(26),
    [sym_identifier] = ACTIONS(29),
    [sym_number] = ACTIONS(32),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_type] = STATE(45),
    [sym_assignment_statement] = STATE(6),
    [sym_return_statement] = STATE(6),
    [sym_expression_statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_expression] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_return] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_number] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_type] = STATE(45),
    [sym_assignment_statement] = STATE(6),
    [sym_return_statement] = STATE(6),
    [sym_expression_statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_expression] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_int] = ACTIONS(23),
    [anon_sym_void] = ACTIONS(23),
    [anon_sym_float] = ACTIONS(23),
    [anon_sym_double] = ACTIONS(23),
    [anon_sym_char] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(37),
    [sym_identifier] = ACTIONS(40),
    [sym_number] = ACTIONS(32),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_function_definition] = STATE(8),
    [sym_type] = STATE(45),
    [sym_assignment_statement] = STATE(8),
    [sym_return_statement] = STATE(8),
    [sym_expression_statement] = STATE(8),
    [sym_variable_declaration] = STATE(8),
    [sym_expression] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_return] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_number] = ACTIONS(11),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(6),
    [sym_function_definition] = STATE(6),
    [sym_type] = STATE(45),
    [sym_assignment_statement] = STATE(6),
    [sym_return_statement] = STATE(6),
    [sym_expression_statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_expression] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_int] = ACTIONS(5),
    [anon_sym_void] = ACTIONS(5),
    [anon_sym_float] = ACTIONS(5),
    [anon_sym_double] = ACTIONS(5),
    [anon_sym_char] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_return] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_number] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(49), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [14] = 2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(53), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [28] = 2,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(57), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [42] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(61), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [56] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(65), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [70] = 2,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(69), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [84] = 2,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(73), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [98] = 2,
    ACTIONS(77), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(75), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [112] = 2,
    ACTIONS(51), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(53), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [126] = 2,
    ACTIONS(59), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(61), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [140] = 2,
    ACTIONS(63), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(65), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [154] = 2,
    ACTIONS(55), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(57), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [168] = 2,
    ACTIONS(47), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(49), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [182] = 2,
    ACTIONS(67), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(69), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [196] = 2,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(73), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [210] = 2,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      sym_number,
    ACTIONS(75), 7,
      anon_sym_int,
      anon_sym_void,
      anon_sym_float,
      anon_sym_double,
      anon_sym_char,
      anon_sym_return,
      sym_identifier,
  [224] = 3,
    ACTIONS(79), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [235] = 3,
    ACTIONS(81), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [246] = 2,
    STATE(37), 1,
      sym_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [254] = 3,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_SEMI,
    STATE(31), 1,
      sym_parameter_list,
  [264] = 3,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      sym_parameter_list,
  [274] = 2,
    STATE(41), 1,
      sym_expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
  [282] = 2,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_compound_statement,
  [289] = 2,
    ACTIONS(91), 1,
      anon_sym_EQ,
    ACTIONS(93), 1,
      anon_sym_SEMI,
  [296] = 2,
    ACTIONS(93), 1,
      anon_sym_SEMI,
    ACTIONS(95), 1,
      anon_sym_EQ,
  [303] = 2,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_compound_statement,
  [310] = 1,
    ACTIONS(99), 1,
      anon_sym_SEMI,
  [314] = 1,
    ACTIONS(101), 1,
      anon_sym_SEMI,
  [318] = 1,
    ACTIONS(103), 1,
      anon_sym_SEMI,
  [322] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [326] = 1,
    ACTIONS(107), 1,
      anon_sym_SEMI,
  [330] = 1,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
  [334] = 1,
    ACTIONS(111), 1,
      anon_sym_SEMI,
  [338] = 1,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
  [342] = 1,
    ACTIONS(115), 1,
      anon_sym_SEMI,
  [346] = 1,
    ACTIONS(117), 1,
      sym_identifier,
  [350] = 1,
    ACTIONS(119), 1,
      sym_identifier,
  [354] = 1,
    ACTIONS(93), 1,
      anon_sym_SEMI,
  [358] = 1,
    ACTIONS(121), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 14,
  [SMALL_STATE(11)] = 28,
  [SMALL_STATE(12)] = 42,
  [SMALL_STATE(13)] = 56,
  [SMALL_STATE(14)] = 70,
  [SMALL_STATE(15)] = 84,
  [SMALL_STATE(16)] = 98,
  [SMALL_STATE(17)] = 112,
  [SMALL_STATE(18)] = 126,
  [SMALL_STATE(19)] = 140,
  [SMALL_STATE(20)] = 154,
  [SMALL_STATE(21)] = 168,
  [SMALL_STATE(22)] = 182,
  [SMALL_STATE(23)] = 196,
  [SMALL_STATE(24)] = 210,
  [SMALL_STATE(25)] = 224,
  [SMALL_STATE(26)] = 235,
  [SMALL_STATE(27)] = 246,
  [SMALL_STATE(28)] = 254,
  [SMALL_STATE(29)] = 264,
  [SMALL_STATE(30)] = 274,
  [SMALL_STATE(31)] = 282,
  [SMALL_STATE(32)] = 289,
  [SMALL_STATE(33)] = 296,
  [SMALL_STATE(34)] = 303,
  [SMALL_STATE(35)] = 310,
  [SMALL_STATE(36)] = 314,
  [SMALL_STATE(37)] = 318,
  [SMALL_STATE(38)] = 322,
  [SMALL_STATE(39)] = 326,
  [SMALL_STATE(40)] = 330,
  [SMALL_STATE(41)] = 334,
  [SMALL_STATE(42)] = 338,
  [SMALL_STATE(43)] = 342,
  [SMALL_STATE(44)] = 346,
  [SMALL_STATE(45)] = 350,
  [SMALL_STATE(46)] = 354,
  [SMALL_STATE(47)] = 358,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_statement, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cpp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cpp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
